# if the location or bin/application path is changed, then update here accordingly..

if [ ${1} == "cleanup" ]; then
    rm -rf ./bin obj Makefile *.make # remove all the file generated by premake
else
    premake5 gmake # currently configured as gmake
    make && ./bin/*/* ${*} # forwarding other argument of bash into application...
fi
